name: Build and Push Docker Images for All Services

on:
  push:
    branches:
      - main # Solo se activa cuando se hace push a la rama main
    paths:
      - 'microservices/**' # Solo se activa si hay cambios en los microservicios
      - 'proxy/**' # Solo se activa si hay cambios en el proxy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - user-auth
          - bus-reservation
          - payment-gateway
          - route-scheduler
          - proxy

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Paso 3: Construir la imagen Docker
      - name: Build Docker image
        run: |
          if [ "${{ matrix.service }}" == "proxy" ]; then
            cd proxy/
          else
            cd microservices/${{ matrix.service }}/
          fi
          docker build -t branvan2k/docker-swarm-microservices-${{ matrix.service }}:latest .

      # Paso 4: Publicar la imagen en Docker Hub
      - name: Push Docker image
        run: |
          docker push branvan2k/docker-swarm-microservices-${{ matrix.service }}:latest
