name: Build and Push Payment Gateway Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'microservices/payment-gateway/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd microservices/user-auth/
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/docker-swarm-microservices-payment-gateway:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/docker-swarm-microservices-payment-gateway:${{ github.sha }}